#!/bin/bash

echo "Microsoft Office Activation Script"
echo "==================================="
echo ""
echo "Microsoft Office 365 has been preinstalled in this container."
echo "To activate Office, you need to sign in with your Microsoft account."
echo ""
echo "Steps to activate:"
echo "1. Launch any Office application (Word, Excel, PowerPoint)"
echo "2. Click 'Sign in' when prompted"
echo "3. Enter your Microsoft account credentials"
echo "4. Follow the activation prompts"
echo ""
echo "If you have a product key instead:"
echo "1. Open an Office app"
echo "2. Go to File > Account > Change Product Key"
echo "3. Enter your 25-character product key"
echo ""
echo "For more information, visit: https://support.microsoft.com/en-us/office/activate-office-5bd38f38-db92-448b-a982-ad170b1e187e"